export { default as GithubIcon } from "./Github.astro"
export { default as LinkedinIcon } from "./Linkedin.astro"
export { default as MailIcon } from "./Mail.astro"
export { default as PhoneIcon } from "./Phone.astro"
export { default as ExperienceIcon } from "./Experience.astro"
export { default as EducationIcon } from "./Education.astro"
export { default as CodeIcon } from "./Code.astro"
export { default as ProfileCheckIcon } from "./ProfileCheck.astro"